<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 11: Clusering seqences from ISOSDB and ISfinder, Made groud truth of preicted gene – IS Project Logbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a14e3238c51140e99ccc48519b6ed9ce.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">IS Project Logbook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../home.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-logs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Logs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-logs">    
        <li>
    <a class="dropdown-item" href="../weekly-logs/week01.html">
 <span class="dropdown-text">Week 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week02.html">
 <span class="dropdown-text">Week 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week03.html">
 <span class="dropdown-text">Week 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week04.html">
 <span class="dropdown-text">Week 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week05.html">
 <span class="dropdown-text">Week 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week06.html">
 <span class="dropdown-text">Week 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week07.html">
 <span class="dropdown-text">Week 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week08.html">
 <span class="dropdown-text">Week 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week09.html">
 <span class="dropdown-text">Week 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week10.html">
 <span class="dropdown-text">Week 10</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../weekly-logs/week11.html">
 <span class="dropdown-text">Week 11</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul>
  <li><a href="#daily-log" id="toc-daily-log" class="nav-link" data-scroll-target="#daily-log">Daily Log</a>
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">07-10-2025</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">09-10-2025</a>
  <ul>
  <li><a href="#run-eris-with-annotation-file" id="toc-run-eris-with-annotation-file" class="nav-link" data-scroll-target="#run-eris-with-annotation-file">Run eris with annotation file</a></li>
  </ul></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">10-10-2025</a>
  <ul>
  <li><a href="#extract-cds-sequence-from-eris" id="toc-extract-cds-sequence-from-eris" class="nav-link" data-scroll-target="#extract-cds-sequence-from-eris">Extract CDS sequence from Eris</a></li>
  </ul></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">12-10-2025</a>
  <ul>
  <li><a href="#using-clustering-mmseq2" id="toc-using-clustering-mmseq2" class="nav-link" data-scroll-target="#using-clustering-mmseq2">Using clustering MMSEQ2</a>
  <ul>
  <li><a href="#extract-cds-sequence-from-complete-chromosome" id="toc-extract-cds-sequence-from-complete-chromosome" class="nav-link" data-scroll-target="#extract-cds-sequence-from-complete-chromosome">Extract CDS sequence from complete chromosome</a></li>
  </ul></li>
  </ul></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 11: Clusering seqences from ISOSDB and ISfinder, Made groud truth of preicted gene</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>Overview</h1>
<section id="daily-log" class="level2">
<h2 class="anchored" data-anchor-id="daily-log">Daily Log</h2>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">07-10-2025</h3>
<ul>
<li>Weekly project meeting
<ul>
<li>Tom has pushed changes of eris</li>
<li>We can try making ground truth of predicted genes, and manually looking</li>
<li>Cluster the sequences from ISOSDB and ISfinder, see how many or much intersection between those two</li>
<li>Dimas needs to start drafting the poster and report, focus on EC958</li>
<li>Important dates:
<ul>
<li>This week: finalise analysis (all above)</li>
<li>20th October: Draft of poster (comments back by Friday 25th)</li>
<li>27th October: Draft of report (comments back by Wednesday 5th Nov)</li>
<li>28th October: poster presentation to Jane</li>
<li>29th October: poster presentation at SCMB</li>
<li>6th November: Seminar presentation (2pm Bris - 3pm Melb)</li>
<li>10th November: final report due</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1">09-10-2025</h3>
<section id="run-eris-with-annotation-file" class="level4">
<h4 class="anchored" data-anchor-id="run-eris-with-annotation-file">Run eris with annotation file</h4>
<div id="fc6168db" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>eris scan ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958.fasta <span class="op">-</span>a ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958_genomic_sorted.cds.edit.bed <span class="op">&gt;</span> eris<span class="op">-</span>outputs<span class="op">/</span>eris_anot.tsv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="32491e9f" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>is_elements <span class="op">=</span> defaultdict(<span class="bu">str</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>cds_features <span class="op">=</span> defaultdict(<span class="bu">list</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"eris-outputs/eris_gfa_shovill_sim.tsv"</span>) <span class="im">as</span> output:</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  head <span class="op">=</span> output.readline()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  rows <span class="op">=</span> output.readlines()</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> r <span class="kw">in</span> rows:</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> r.split(<span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> row[<span class="dv">2</span>] <span class="op">==</span> <span class="st">"mobile_element"</span>:</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>      is_elements[row[<span class="dv">1</span>]] <span class="op">=</span> row[<span class="dv">15</span>]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> r <span class="kw">in</span> rows:</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> r.split(<span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> row[<span class="dv">2</span>] <span class="op">==</span> <span class="st">"CDS"</span>:</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>      contig <span class="op">=</span> row[<span class="dv">3</span>]</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>      start <span class="op">=</span> row[<span class="dv">4</span>]</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>      end <span class="op">=</span> row[<span class="dv">5</span>]</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>      seq_strand <span class="op">=</span> row[<span class="dv">6</span>]</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>      effect <span class="op">=</span> row[<span class="dv">12</span>]</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>      location <span class="op">=</span> row[<span class="dv">10</span>]</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>      strand <span class="op">=</span> row[<span class="dv">11</span>].replace(<span class="st">" "</span>, <span class="st">"_"</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>      is_name <span class="op">=</span> is_elements[row[<span class="dv">8</span>]]</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>      cds_features[row[<span class="dv">1</span>]]<span class="op">=</span> [contig, start, end, seq_strand, effect, location, strand, is_name]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2">10-10-2025</h3>
<p>the goal is to search where are the cds that are might be impated (from eris), how similiar this prediction against truth, in terms of location the IS elements to the information from chromosome sequence</p>
<p>First approach using mapping:</p>
<ul>
<li>First I extracted the predicted CDS from eris (GFA) in fasta fomat, in header I added information on what the element effect, location, and nearest IS name</li>
<li>I got the fasta sequence with useful information, then I mapped them against EC958 chromosome, look where are predicted CDS from <strong>draft assembly</strong> relative to the chromosome</li>
<li>Extract the location where the predicted CDS mapped, then I intersect them with “ground truth CDS” with at least 50% intersection</li>
<li>Those that passed through the fraction threshold, I added them a flank 500 bp each end</li>
<li>Then I intersect them against <strong>IS ground truth</strong></li>
<li>From there, we can answer the concordance of the IS elements and CDS relationship, are the corsonding IS the same? right?</li>
</ul>
<section id="extract-cds-sequence-from-eris" class="level4">
<h4 class="anchored" data-anchor-id="extract-cds-sequence-from-eris">Extract CDS sequence from Eris</h4>
<p>Identify CDS sequence that may be imacted by insertion from Eris, and extract the coding sequence from the gfa file</p>
<div id="eefc3baf" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> eris.io <span class="im">import</span> SeqFile</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> eris.seq <span class="im">import</span> Record</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>the_gfa <span class="op">=</span> SeqFile(<span class="st">"../../data/ecoli/assembly-simulated/shovill-outputs/contigs.gfa"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>nodes_seq <span class="op">=</span> defaultdict(<span class="bu">str</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> entry <span class="kw">in</span> the_gfa:</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> <span class="bu">isinstance</span>(entry, Record):</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    nodes_seq[entry.<span class="bu">id</span>] <span class="op">=</span> entry.seq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="5025bf56" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> writeFasta(seqname: <span class="bu">str</span>, sequence: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">"""Write one sequence in FASTA format to a string and return it. This will split the sequence per 60 bp per line.</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">  """</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  fasta <span class="op">=</span> <span class="st">"&gt;"</span> <span class="op">+</span> seqname <span class="op">+</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  nlines <span class="op">=</span> <span class="bu">int</span>(math.ceil((<span class="bu">len</span>(sequence) <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> <span class="dv">60</span> <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(nlines):</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>      lineofseq <span class="op">=</span> <span class="st">""</span>.join(sequence[i <span class="op">*</span> <span class="dv">60</span> : (i <span class="op">+</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">60</span>]) <span class="op">+</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>      fasta <span class="op">+=</span> lineofseq</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> fasta</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reverse_complement(sequence: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">"""</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co">  make reverse complement of the input sequence</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="co">  """</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  result <span class="op">=</span> <span class="st">""</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  complement <span class="op">=</span> {<span class="st">"A"</span> : <span class="st">"T"</span>, <span class="st">"T"</span>: <span class="st">"A"</span>, <span class="st">"G"</span>: <span class="st">"C"</span>, <span class="st">"C"</span>: <span class="st">"G"</span>}</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> b <span class="kw">in</span> sequence:</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    result <span class="op">+=</span> complement[b]</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> result[::<span class="op">-</span><span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fa16b6e9" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re, os</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    os.remove(<span class="st">"cds_gfa_shovill_is.fna"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">FileNotFoundError</span>:</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">pass</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> feat, info <span class="kw">in</span> cds_features.items():</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  name <span class="op">=</span> <span class="st">"|"</span>.join([feat, info[<span class="dv">0</span>], info[<span class="dv">4</span>], info[<span class="dv">5</span>], info[<span class="dv">6</span>], info[<span class="dv">7</span>]])</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  seq <span class="op">=</span> nodes_seq[info[<span class="dv">0</span>]]</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># if the feature has minus stran, we reverse complement the sequence</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> info[<span class="dv">3</span>] <span class="op">==</span> <span class="st">"-1"</span>:</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    seq <span class="op">=</span> reverse_complement(seq)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  start, end <span class="op">=</span> <span class="bu">int</span>(info[<span class="dv">1</span>]), <span class="bu">int</span>(info[<span class="dv">2</span>])</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  subseq <span class="op">=</span> <span class="bu">str</span>(seq[start:end])</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  fasta <span class="op">=</span> writeFasta(name, subseq)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="cf">with</span> <span class="bu">open</span>(<span class="st">"cds_gfa_shovill_is.fna"</span>, <span class="st">"a"</span>) <span class="im">as</span> output:</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    output.write(fasta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="4acad256" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>wc <span class="op">-</span>l ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958_genomic_sorted.cds.edit.bed <span class="co"># this is cds bed file from NCBI</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>grep <span class="st">"^&gt;"</span> cds_gfa_shovill_is.fna <span class="op">|</span> wc <span class="op">-</span>l</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    5093 ../../data/ecoli/EC958_genomic_sorted.cds.edit.bed
     183</code></pre>
</div>
</div>
<p>so there are 5093 CDS in total from chromosome sequence, and 183 that might be impacted by insertions (near identifeied IS)</p>
<p>Let’s search where those 183 cds located in the genome, and are the location with respect of insertion elements similar or no</p>
<p>First, i think we can just map the <strong>predicted cds (from eris)</strong>.. and look where are they, relative to the chromosome, then we can look whether there are annotated IS near them, right? 🤔</p>
<p><strong>map cds from eris to chromosome, using minimap:</strong></p>
<div id="84630350" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using preset short read, because cds sequences are short</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>minimap2 <span class="op">-</span>x sr ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958.fasta cds_gfa_shovill_is.fna <span class="op">&gt;</span> cds_is_to_chrom.paf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[M::mm_idx_gen::0.071*1.10] collected minimizers
[M::mm_idx_gen::0.085*1.38] sorted minimizers
[M::main::0.085*1.38] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.085*1.38] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.090*1.36] distinct minimizers: 834905 (98.89% are singletons); average occurrences: 1.020; average spacing: 6.000; total length: 5109767
[M::worker_pipeline::0.093*1.39] mapped 183 sequences
[M::main] Version: 2.30-r1287
[M::main] CMD: minimap2 -x sr ../../data/ecoli/EC958.fasta cds_gfa_shovill_is.fna
[M::main] Real time: 0.096 sec; CPU: 0.133 sec; Peak RSS: 0.077 GB</code></pre>
</div>
</div>
<p>how many cds from eris were successfully mapped to chrom sequence?</p>
<div id="1a16ceb2" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>wc <span class="op">-</span>l cds_is_to_chrom.paf</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>cut <span class="op">-</span>f <span class="dv">1</span> cds_is_to_chrom.paf  <span class="op">|</span> sort <span class="op">|</span> uniq <span class="op">|</span> wc <span class="op">-</span>l</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     183 cds_is_to_chrom.paf
     183</code></pre>
</div>
</div>
<p>all of them, each of them is mapped uniqely..</p>
<p>extract the location information, where are they realtive to the chromosome coordinate and also corresponding eris information (make a bed file)</p>
<div id="fcd15d76" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4th field is for query name (cds and coresponding insertion info from eris)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 5th field is for alignment score from minimap</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 6th strand info from minimap2</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>awk <span class="op">-</span>v OFS<span class="op">=</span><span class="st">"</span><span class="ch">\t</span><span class="st">"</span> <span class="st">'{print $6, $8, $9, $1, $12, $5}'</span> cds_is_to_chrom.paf <span class="op">&gt;</span> cds_is_to_chrom.bed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>look intersection between mapped cds here with cds coordinate from the truth (ncbi),</li>
<li>add flank at both ends for each entries, and instersect them again with IS locations (reanotatated truth). Add flank so that we know how close the cds (predicted from gfa) to the IS elements (from truth chromosome) are</li>
<li>save into file for checking similarty on the location, strandness, and we can assess how well eris predict the location</li>
</ul>
<div id="bbe92a17" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sort the entry</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>bedtools sort <span class="op">-</span>i cds_is_to_chrom.bed <span class="op">&gt;</span> cds_is_to_chrom.<span class="bu">sorted</span>.bed</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># intersect them with known cds, with at least 50% fraction</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>bedtools intersect <span class="op">-</span>a cds_is_to_chrom.<span class="bu">sorted</span>.bed <span class="op">-</span>b ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958_genomic_sorted.cds.edit.bed <span class="op">-</span>f <span class="fl">0.5</span> <span class="op">-</span>wa <span class="op">|</span> bedtools slop <span class="op">-</span>i <span class="op">-</span> <span class="op">-</span>g ec958.genome.size <span class="op">-</span>b <span class="dv">1000</span> <span class="op">|</span> bedtools intersect <span class="op">-</span>a <span class="op">-</span> <span class="op">-</span>b ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>ec958_IS.reannotated.<span class="bu">sorted</span>.bed <span class="op">-</span>wa <span class="op">-</span>wb <span class="op">&gt;</span> cds_gfa_intersect_IS_truth.bed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="14dc8103" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>cut <span class="op">-</span>f <span class="dv">4</span> cds_gfa_intersect_IS_truth.bed <span class="op">|</span> sort <span class="op">|</span> uniq <span class="op">|</span> wc <span class="op">-</span>l</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     125</code></pre>
</div>
</div>
<p>From 183 cds, we have 125 that passed through series of intersection step. Most of them (if not all) did not pass when we intersect them (added with flank 1000 bp at both ends) to IS. Not sure but bedtools subcommand to extend the both flanks is <code>bedtools slop</code> not <code>bedtools flank</code>.</p>
<p>Some predicted CDS that don’t pass the intersection step look like this:</p>
<p><img src="pictures/cds_wrong_predicted.png" class="img-fluid" alt="No overlap with truth CDS"> <img src="pictures/cds_misplaced.png" class="img-fluid" alt="Little overlap with truth CDS"></p>
<p>Check on the assignment of element location relative to the CDS. We assess the report come from eris using the ground truth IS and full chromosome.</p>
<p>Eris defines element_location as: <strong>Signifies the relative location of the Element from the current context</strong>.</p>
<p>So I can check if:</p>
<p>Inside: the predicted CDS is part of truth IS Downstream: the predicted CDS has IS element at its downstream (after the cds) Upstream: the predicted CDS has IS element at its upstream (after the cds) Flanking: the predicted CDS has an IS element overlapping it, but not fully inside.</p>
<div id="58b899ae" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>cds_elements <span class="op">=</span> defaultdict(<span class="bu">str</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"cds_gfa_intersect_IS_truth.bed"</span>) <span class="im">as</span> entries:</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  entries <span class="op">=</span> entries.readlines()</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> entry <span class="kw">in</span> entries:</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    entry <span class="op">=</span> entry.split(<span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    cds_start <span class="op">=</span> <span class="bu">int</span>(entry[<span class="dv">1</span>]) <span class="op">+</span> <span class="dv">1000</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    cds_end <span class="op">=</span> <span class="bu">int</span>(entry[<span class="dv">2</span>]) <span class="op">-</span> <span class="dv">1000</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    is_start <span class="op">=</span> <span class="bu">int</span>(entry[<span class="dv">7</span>])</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    is_end <span class="op">=</span> <span class="bu">int</span>(entry[<span class="dv">8</span>])</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    predicted_location <span class="op">=</span> entry[<span class="dv">3</span>].split(<span class="st">"|"</span>)[<span class="dv">3</span>]</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    is_precited <span class="op">=</span> entry[<span class="dv">3</span>].split(<span class="st">"|"</span>)[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    is_truth <span class="op">=</span> entry[<span class="dv">9</span>]</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    predicted_cds_strand <span class="op">=</span> entry[<span class="dv">5</span>]</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    is_strand <span class="op">=</span> entry[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    length_cds <span class="op">=</span> cds_end <span class="op">-</span> cds_start</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># inside</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> predicted_location <span class="op">==</span> <span class="st">"inside"</span>:</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> entry[<span class="dv">3</span>] <span class="kw">not</span> <span class="kw">in</span> cds_elements:</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>        cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"False"</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> is_precited <span class="op">==</span> is_truth.split(<span class="st">"_"</span>)[<span class="dv">0</span>]:</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> cds_start <span class="op">&gt;=</span> is_start <span class="kw">and</span> cds_end <span class="op">&lt;=</span> is_end: <span class="co"># part of the IS hit</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>          cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"True"</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>          <span class="cf">continue</span></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># downstream</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> predicted_location <span class="op">==</span> <span class="st">"downstream"</span>:</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> entry[<span class="dv">3</span>] <span class="kw">not</span> <span class="kw">in</span> cds_elements:</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>        cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"False"</span></span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> predicted_cds_strand <span class="op">==</span> <span class="st">"+"</span>:</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> is_precited <span class="op">==</span> is_truth.split(<span class="st">"_"</span>)[<span class="dv">0</span>]:</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>          check <span class="op">=</span> <span class="bu">max</span>(<span class="dv">0</span>, cds_end <span class="op">-</span> is_start)</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>          <span class="cf">if</span> check <span class="op">/</span> length_cds <span class="op">&lt;</span> <span class="fl">0.8</span>:</span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>            cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"True"</span></span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>      <span class="cf">elif</span> predicted_cds_strand <span class="op">==</span> <span class="st">"-"</span>:</span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> is_precited <span class="op">==</span> is_truth.split(<span class="st">"_"</span>)[<span class="dv">0</span>]:</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>          check <span class="op">=</span> <span class="bu">max</span>(<span class="dv">0</span>, is_end <span class="op">-</span> cds_start)</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a>          <span class="cf">if</span> check <span class="op">/</span> length_cds <span class="op">&lt;</span> <span class="fl">0.8</span>:</span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>              cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"True"</span></span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a>              <span class="cf">continue</span></span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a>    <span class="co"># upstream</span></span>
<span id="cb16-47"><a href="#cb16-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> predicted_location <span class="op">==</span> <span class="st">"upstream"</span>:</span>
<span id="cb16-48"><a href="#cb16-48" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> entry[<span class="dv">3</span>] <span class="kw">not</span> <span class="kw">in</span> cds_elements:</span>
<span id="cb16-49"><a href="#cb16-49" aria-hidden="true" tabindex="-1"></a>        cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"False"</span></span>
<span id="cb16-50"><a href="#cb16-50" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> predicted_cds_strand <span class="op">==</span> <span class="st">"+"</span>:</span>
<span id="cb16-51"><a href="#cb16-51" aria-hidden="true" tabindex="-1"></a>          <span class="cf">if</span> is_precited <span class="op">==</span> is_truth.split(<span class="st">"_"</span>)[<span class="dv">0</span>]:</span>
<span id="cb16-52"><a href="#cb16-52" aria-hidden="true" tabindex="-1"></a>            check <span class="op">=</span> <span class="bu">max</span>(<span class="dv">0</span>, is_end <span class="op">-</span> cds_start)</span>
<span id="cb16-53"><a href="#cb16-53" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> check <span class="op">/</span> length_cds <span class="op">&lt;</span> <span class="fl">0.8</span>:</span>
<span id="cb16-54"><a href="#cb16-54" aria-hidden="true" tabindex="-1"></a>                cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"True"</span></span>
<span id="cb16-55"><a href="#cb16-55" aria-hidden="true" tabindex="-1"></a>                <span class="cf">continue</span></span>
<span id="cb16-56"><a href="#cb16-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-57"><a href="#cb16-57" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> predicted_cds_strand <span class="op">==</span> <span class="st">"-"</span>:</span>
<span id="cb16-58"><a href="#cb16-58" aria-hidden="true" tabindex="-1"></a>          <span class="cf">if</span> is_precited <span class="op">==</span> is_truth.split(<span class="st">"_"</span>)[<span class="dv">0</span>]:</span>
<span id="cb16-59"><a href="#cb16-59" aria-hidden="true" tabindex="-1"></a>            check <span class="op">=</span> <span class="bu">max</span>(<span class="dv">0</span>, cds_end <span class="op">-</span> is_start)</span>
<span id="cb16-60"><a href="#cb16-60" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> check <span class="op">/</span> length_cds <span class="op">&lt;</span> <span class="fl">0.8</span>:</span>
<span id="cb16-61"><a href="#cb16-61" aria-hidden="true" tabindex="-1"></a>                cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"True"</span></span>
<span id="cb16-62"><a href="#cb16-62" aria-hidden="true" tabindex="-1"></a>                <span class="cf">continue</span></span>
<span id="cb16-63"><a href="#cb16-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-64"><a href="#cb16-64" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> predicted_location <span class="op">==</span> <span class="st">"flanking"</span>:</span>
<span id="cb16-65"><a href="#cb16-65" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> entry[<span class="dv">3</span>] <span class="kw">not</span> <span class="kw">in</span> cds_elements:</span>
<span id="cb16-66"><a href="#cb16-66" aria-hidden="true" tabindex="-1"></a>        cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"False"</span></span>
<span id="cb16-67"><a href="#cb16-67" aria-hidden="true" tabindex="-1"></a>    overlap <span class="op">=</span> <span class="bu">max</span>(<span class="dv">0</span>, <span class="bu">min</span>(cds_end, is_end) <span class="op">-</span> <span class="bu">max</span>(cds_start, is_start))</span>
<span id="cb16-68"><a href="#cb16-68" aria-hidden="true" tabindex="-1"></a>    overlap_fraction <span class="op">=</span> overlap <span class="op">/</span> length_cds</span>
<span id="cb16-69"><a href="#cb16-69" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> is_precited <span class="op">==</span> is_truth.split(<span class="st">"_"</span>)[<span class="dv">0</span>]:</span>
<span id="cb16-70"><a href="#cb16-70" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="fl">0.8</span> <span class="op">&lt;=</span> overlap_fraction <span class="op">&lt;</span> <span class="dv">1</span>:</span>
<span id="cb16-71"><a href="#cb16-71" aria-hidden="true" tabindex="-1"></a>            cds_elements[entry[<span class="dv">3</span>]] <span class="op">=</span> <span class="st">"True"</span></span>
<span id="cb16-72"><a href="#cb16-72" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb16-73"><a href="#cb16-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-74"><a href="#cb16-74" aria-hidden="true" tabindex="-1"></a>true_count <span class="op">=</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> v <span class="kw">in</span> cds_elements.values() <span class="cf">if</span> v <span class="op">==</span> <span class="st">"True"</span>)</span>
<span id="cb16-75"><a href="#cb16-75" aria-hidden="true" tabindex="-1"></a>false_count <span class="op">=</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> v <span class="kw">in</span> cds_elements.values() <span class="cf">if</span> v <span class="op">==</span> <span class="st">"False"</span>)</span>
<span id="cb16-76"><a href="#cb16-76" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> <span class="bu">len</span>(cds_elements)</span>
<span id="cb16-77"><a href="#cb16-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-78"><a href="#cb16-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-79"><a href="#cb16-79" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ele, val <span class="kw">in</span> cds_elements.items():</span>
<span id="cb16-80"><a href="#cb16-80" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(ele, val)</span>
<span id="cb16-81"><a href="#cb16-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-82"><a href="#cb16-82" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total CDS: </span><span class="sc">{</span>total<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-83"><a href="#cb16-83" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Correct assignments: </span><span class="sc">{</span>true_count<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-84"><a href="#cb16-84" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Incorrect assignments: </span><span class="sc">{</span>false_count<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-85"><a href="#cb16-85" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy: </span><span class="sc">{</span>true_count <span class="op">/</span> total<span class="sc">:.2%}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1244700_00882|1244700|-|inside|same_strand|ISEc23 True
1244700_00883|1244700|-|inside|same_strand|ISEc23 True
1244816_01151|1244816|-|inside|same_strand|ISEc23 True
1176191_00082|1176191|-|flanking|opposite_strand|ISEc23 False
1245002_02024|1245002|disrupted|upstream|same_strand|ISCfr4 False
1245002_02025|1245002|-|inside|same_strand|ISCfr4 True
1245002_02026|1245002|-|downstream|same_strand|ISCfr4 False
1245002_02031|1245002|-|inside|opposite_strand|ISSen3 False
1244912_01169|1244912|-|flanking|same_strand|ISEc12 False
1245096_04606|1245096|-|inside|same_strand|ISEc1 True
1015060_00032|1015060|-|inside|same_strand|IS1397 True
1208211_00117|1208211|-|flanking|opposite_strand|IS1397 False
1234872_00176|1234872|-|inside|same_strand|IS1397 True
1241248_00251|1241248|-|inside|same_strand|IS1397 True
1244764_01147|1244764|-|inside|same_strand|IS609 True
832167_00019|832167|-|flanking|opposite_strand|IS609 False
1244458_00450|1244458|disrupted|upstream|opposite_strand|IS609 True
1244458_00486|1244458|-|flanking|same_strand|IS1397 False
1244458_00449|1244458|-|inside|same_strand|IS609 False
1244160_00403|1244160|-|inside|same_strand|IS1397 True
1208964_00119|1208964|-|inside|same_strand|IS1397 True
1216050_00137|1216050|-|inside|same_strand|IS1397 True
1241248_00250|1241248|-|inside|opposite_strand|IS1397 True
1244664_00858|1244664|-|flanking|same_strand|IS1397 False
1244018_00385|1244018|-|downstream|same_strand|IS200C False
1221552_00145|1221552|-|inside|same_strand|IS200C True
1241860_00257|1241860|-|flanking|opposite_strand|IS200C False
1244910_01167|1244910|disrupted|upstream|same_strand|IS200C False
1245062_04536|1245062|-|downstream|opposite_strand|ISEc38 True
1244402_00441|1244402|-|inside|same_strand|IS100kyp True
1244402_00440|1244402|-|inside|same_strand|IS100kyp True
1244402_00445|1244402|-|upstream|same_strand|ISEc20 False
1116087_00050|1116087|-|inside|same_strand|ISEc23 True
1240840_00244|1240840|-|flanking|opposite_strand|ISEc12 False
1221552_00144|1221552|-|inside|same_strand|IS200C True
1245038_03183|1245038|-|flanking|opposite_strand|IS1A False
1245136_04886|1245136|-|flanking|same_strand|IS1A False
1245136_04885|1245136|-|inside|opposite_strand|IS1B False
1245046_03736|1245046|-|flanking|opposite_strand|IS1A False
1245022_02114|1245022|disrupted|downstream|same_strand|MITEEc1 False
1245022_02113|1245022|disrupted|upstream|same_strand|MITEEc1 False
1171599_00078|1171599|-|inside|same_strand|IS1A True
1245138_04887|1245138|-|flanking|same_strand|IS1A False
1236016_00186|1236016|-|flanking|opposite_strand|IS1A False
1208153_00116|1208153|-|inside|same_strand|IS1A True
1244936_01278|1244936|-|flanking|opposite_strand|IS1A False
1244936_01276|1244936|-|downstream|opposite_strand|IS1203 True
1244936_01275|1244936|-|inside|same_strand|IS1203 True
1244936_01274|1244936|-|inside|same_strand|IS1203 True
1243600_00315|1243600|-|inside|same_strand|IS600 False
1243600_00328|1243600|-|inside|same_strand|IS3411 False
1245106_04649|1245106|-|flanking|same_strand|IS1F False
1243600_00316|1243600|disrupted|upstream|same_strand|IS600 False
1243600_00327|1243600|-|inside|same_strand|ISKox3 True
1242602_00264|1242602|-|inside|same_strand|IS30 True
1242602_00265|1242602|-|flanking|opposite_strand|IS600 False
1244674_00860|1244674|-|inside|same_strand|IS682 False
1244674_00861|1244674|-|inside|same_strand|IS682 False
1244674_00862|1244674|-|inside|same_strand|IS682 False
1244674_00878|1244674|-|upstream|opposite_strand|ISEc45 False
1244674_00874|1244674|-|downstream|same_strand|IS2 False
1244674_00873|1244674|-|inside|same_strand|IS2 True
1244674_00872|1244674|-|inside|same_strand|IS2 True
1244674_00871|1244674|disrupted|upstream|same_strand|IS2 False
1244674_00863|1244674|-|upstream|opposite_strand|IS682 True
1244674_00879|1244674|-|inside|same_strand|ISEch14 False
1244674_00880|1244674|-|inside|same_strand|ISEch14 False
1125059_00056|1125059|-|inside|same_strand|ISEc8 False
1240608_00243|1240608|-|inside|same_strand|ISEc22 True
1243212_00271|1243212|-|flanking|same_strand|ISEc22 True
1244994_01721|1244994|-|upstream|same_strand|ISKpn42 False
1244994_01722|1244994|-|inside|same_strand|ISKpn42 False
1244994_01723|1244994|-|inside|same_strand|ISEc10 True
1244994_01724|1244994|-|inside|same_strand|ISEc10 True
1244994_01725|1244994|-|downstream|same_strand|ISEc10 False
1244434_00447|1244434|-|inside|same_strand|ISEc52 True
1206755_00112|1206755|-|upstream|opposite_strand|IS600 False
1245082_04546|1245082|-|inside|same_strand|ISEc52 True
1245080_04545|1245080|-|inside|same_strand|ISEc52 True
1244570_00584|1244570|disrupted|downstream|opposite_strand|IS609 True
1244764_01146|1244764|disrupted|upstream|same_strand|IS609 False
1244706_00887|1244706|-|inside|same_strand|IS1F True
1202947_00109|1202947|-|inside|same_strand|IS1X2 False
1215098_00134|1215098|-|inside|same_strand|IS1F True
1236482_00188|1236482|-|inside|same_strand|IS1F True
1245106_04640|1245106|disrupted|downstream|same_strand|ISSen10 False
1245106_04639|1245106|-|inside|same_strand|ISSen10 True
1245106_04638|1245106|disrupted|upstream|same_strand|ISSen10 False
1002621_00031|1002621|-|flanking|opposite_strand|IS3411 False
1244656_00832|1244656|disrupted|upstream|opposite_strand|IS3411 False
1244656_00833|1244656|-|inside|same_strand|ISEc43 False
1244656_00844|1244656|-|inside|same_strand|ISCro1 True
1244656_00843|1244656|-|upstream|opposite_strand|ISCro1 False
1244656_00845|1244656|-|inside|same_strand|ISCro1 True
1244656_00846|1244656|-|inside|same_strand|ISCro1 True
1244656_00837|1244656|disrupted|upstream|same_strand|ISEc49 False
1245118_04670|1245118|-|flanking|opposite_strand|ISEc23 False
1244700_00884|1244700|-|inside|same_strand|ISEc23 True
1159225_00072|1159225|-|inside|same_strand|ISEc23 True
1245048_03750|1245048|-|flanking|opposite_strand|ISSd1 False
1245048_03746|1245048|-|inside|same_strand|ISEc9 True
1245048_03748|1245048|upregulated|downstream|same_strand|ISEc9 False
1243758_00330|1243758|-|inside|same_strand|ISSd1 False
976171_00026|976171|-|flanking|same_strand|IS600 False
1228204_00159|1228204|-|inside|same_strand|IS600 True
1206755_00111|1206755|-|inside|same_strand|IS600 True
1243586_00314|1243586|-|inside|same_strand|ISEc52 False
1158833_00071|1158833|-|inside|same_strand|IS1F True
1244320_00406|1244320|-|downstream|opposite_strand|ISEc8 True
1244320_00405|1244320|-|inside|same_strand|ISEc8 True
1244320_00407|1244320|-|inside|same_strand|IS1F False
1244320_00408|1244320|-|flanking|opposite_strand|IS1X2 False
1234604_00174|1234604|-|inside|same_strand|ISEc8 True
1235120_00177|1235120|-|flanking|opposite_strand|ISEc8 False
1236644_00191|1236644|-|inside|same_strand|ISEc8 True
1236644_00190|1236644|-|inside|same_strand|ISEc8 True
1236644_00189|1236644|-|inside|same_strand|ISEc8 True
1244742_00933|1244742|-|inside|same_strand|ISEc12 True
1244742_00934|1244742|-|inside|same_strand|ISEc12 True
1245024_02247|1245024|-|downstream|same_strand|IS911 False
1245024_02220|1245024|-|upstream|same_strand|ISSen1 False
1245024_02221|1245024|disrupted|downstream|same_strand|ISSen1 False
1244890_01166|1244890|-|flanking|same_strand|IS1F False
1244638_00699|1244638|-|inside|same_strand|ISEc53 True
1244638_00698|1244638|-|inside|same_strand|ISEc53 True
Total CDS: 125
Correct assignments: 61
Incorrect assignments: 64
Accuracy: 48.80%
</code></pre>
</div>
</div>
<p>We look closer, most of the incorrect assigments mistakenly assigned downstream location to upstream location, and vice versa.</p>
<p><img src="pictures/IS200C_wrong.png" class="img-fluid" alt="IS200C"> <em>1244910_01167</em> has IS element IS200C at its downstream, and <em>1244018_00385</em> has IS element IS200C at its upstream</p>
<p>but eris says: 1244910_01167|1244910|disrupted|upstream|same_strand|IS200C False 1244018_00385|1244018|-|downstream|same_strand|IS200C False</p>
<p>CDS <em>1244910_01167</em> has IS element IS200C at its upstream, <em>1244018_00385</em> has IS element IS200C at its downstream.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/ISEc9_upr.png" class="img-fluid figure-img"></p>
<figcaption>ISEc9</figcaption>
</figure>
</div>
<p>the ISEc9 lies at the upstream of the CDS, but eris predicted at downstream.</p>
<p>1245048_03748|1245048|upregulated|downstream|same_strand|ISEc9 False</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/ISCfr4_dist_wrong.png" class="img-fluid figure-img"></p>
<figcaption>ISCfr4</figcaption>
</figure>
</div>
<p>Eris predicted: 1245002_02024|1245002|disrupted|upstream|same_strand|ISCfr4 False 1245002_02025|1245002|-|inside|same_strand|ISCfr4 True 1245002_02026|1245002|-|downstream|same_strand|ISCfr4 False</p>
<p>but: ISCfr4 lies at downstream of 1245002_02024, and it is at upstream 1245002_02026</p>
<p><img src="pictures/ISEc53_no.png" class="img-fluid" alt="ISEc53"> Eris predicted ISEc53 at the downstream of the CDS, but it is at its upstream</p>
<p><img src="pictures/ISSen10.png" class="img-fluid" alt="ISSen10"> Eris predicted ISSen10 at the upstream of the CDS 1245106_04638, but it is at downstrem of it.</p>
<p><img src="pictures/IS2_confusing.png" class="img-fluid" alt="IS2"> Eris also predicted wrong here. It should be: IS2 lies at the downstream of 1244674_00871 and at the upstream of 1244674_00874</p>
<p>Several correct assignments by Eris here:</p>
<p><img src="pictures/ISEc38_correct.png" class="img-fluid" alt="ISEc38"> 1245062_04536|1245062|-|downstream|opposite_strand|ISEc38 True</p>
<p>ISEc38 element is at the downstream of CDS 1245062_04536</p>
<p><img src="pictures/ISEc8_true.png" class="img-fluid" alt="ISEc8"> 1244320_00406|1244320|-|downstream|opposite_strand|ISEc8 True</p>
<p>ISEc8 lies at the downstream of CDS 1244320_00406</p>
<p><img src="pictures/IS609_corr_in.png" class="img-fluid" alt="IS609"> 1244570_00584|1244570|disrupted|downstream|opposite_strand|IS609 True</p>
<p>Correct as the IS609 elements appear at the downstream of 1244570_00584</p>
<p>Check the entries that don’t pass intersection with IS, in theory they should not be reported for the insertion effect (because the proximity more than 150), no?</p>
<p><img src="pictures/ISEc1_far.png" class="img-fluid" alt="ISEc1"> Eris still predicted CDS 1245096_04607 will be disrupted, although it far from the nearest IS element ISec1 (&gt;150 bp) in the full chromosome</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/MITEEc1.png" class="img-fluid figure-img"></p>
<figcaption>MITEEc1</figcaption>
</figure>
</div>
<p>Eris the detec IS that don’t exist in truth, so they don’t overlap</p>
<p><strong>Summary</strong></p>
<ul>
<li>All the exracted predicted CDS from gfa file were succesfully mapped to the reference sequence uniquely.</li>
<li>All those sequences intersect with at least small fraction with known/truth CDS</li>
<li>Based on the checking using IGV and phython cod above, I can say:
<ul>
<li>Most of the time, eris correctly predicted the CDS are inside the IS</li>
<li>Most of the time, eris incorrectly predicted between downstream and upstream, confised between two</li>
<li>Most of the time eris correctly predicted the corresponding IS for each predicted CDS</li>
</ul></li>
<li>Some CDS are missc</li>
</ul>
</section>
</section>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3">12-10-2025</h3>
<section id="using-clustering-mmseq2" class="level4">
<h4 class="anchored" data-anchor-id="using-clustering-mmseq2">Using clustering MMSEQ2</h4>
<p><strong>cluster the ISfinder and ISOSDB using mmseqs2</strong></p>
<div id="0aa605d1" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>cat ..<span class="op">/</span>..<span class="op">/</span>ISOSDB.V3.fna ..<span class="op">/</span>..<span class="op">/</span>eris<span class="op">/</span>src<span class="op">/</span>eris<span class="op">/</span>data<span class="op">/</span>IS.fna <span class="op">&gt;</span> combined_ISOSDB_ISfinder.fna</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>mmseqs easy<span class="op">-</span>cluster combined_ISOSDB_ISfinder.fna clusterIS tmp <span class="op">--</span><span class="bu">min</span><span class="op">-</span>seq<span class="op">-</span><span class="bu">id</span> <span class="fl">0.8</span> <span class="op">-</span>c <span class="fl">0.8</span> <span class="op">-</span>s <span class="dv">7</span> <span class="op">--</span>threads <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Look for the intersections</strong></p>
<div id="94e5bf2e" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> defaultdict(<span class="bu">list</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"clusterIS_cluster.tsv"</span>) <span class="im">as</span> entries:</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> entry <span class="kw">in</span> entries.readlines():</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    cluster, member <span class="op">=</span> entry.split(<span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    clusters[cluster].append(member)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"There are </span><span class="sc">{</span><span class="bu">len</span>(clusters)<span class="sc">}</span><span class="ss"> clusters"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># classify clusters</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>isosdb_only <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>isfinder_only <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>both <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>isosdb_clusters <span class="op">=</span> []</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>isfinder_clusters <span class="op">=</span> []</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>both_clusters <span class="op">=</span> []</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cluster_id, members <span class="kw">in</span> clusters.items():</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    has_isosdb <span class="op">=</span> <span class="bu">any</span>(m.startswith(<span class="st">"ISOSDB"</span>) <span class="cf">for</span> m <span class="kw">in</span> members)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>    has_isfinder <span class="op">=</span> <span class="bu">any</span>(<span class="kw">not</span> m.startswith(<span class="st">"ISOSDB"</span>) <span class="cf">for</span> m <span class="kw">in</span> members)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> has_isosdb <span class="kw">and</span> has_isfinder:</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>        both <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>        both_clusters.append(cluster_id)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> has_isosdb:</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>        isosdb_only <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>        isosdb_clusters.append(cluster_id)</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> has_isfinder:</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>        isfinder_only <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>        isfinder_clusters.append(cluster_id)</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib_venn <span class="im">import</span> venn2</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a><span class="co"># sizes</span></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>only_isosdb <span class="op">=</span> <span class="bu">len</span>(isosdb_clusters)</span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>only_isfinder <span class="op">=</span> <span class="bu">len</span>(isfinder_clusters)</span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>overlap <span class="op">=</span> <span class="bu">len</span>(both_clusters)</span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Venn diagram</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">5</span>,<span class="dv">5</span>))</span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a>venn2(subsets<span class="op">=</span>(only_isosdb, only_isfinder, overlap), </span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>      set_labels<span class="op">=</span>(<span class="st">"ISOSDB"</span>, <span class="st">"isfinder DB"</span>))</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Cluster overlap"</span>)</span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters with both ISOSDB and ISfinder:"</span>, both)</span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters only ISOSDB:"</span>, isosdb_only)</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters only ISfinder:"</span>, isfinder_only)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 16655 clusters</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="week11_files/figure-html/cell-15-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Clusters with both ISOSDB and ISfinder: 1775
Clusters only ISOSDB: 12397
Clusters only ISfinder: 2483</code></pre>
</div>
</div>
<section id="extract-cds-sequence-from-complete-chromosome" class="level5">
<h5 class="anchored" data-anchor-id="extract-cds-sequence-from-complete-chromosome">Extract CDS sequence from complete chromosome</h5>
<p>we can use seqkit to extract sequence from fasta format</p>
<div id="ce73b81e" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>seqkit subseq <span class="op">--</span>bed ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958_genomic_sorted.cds.edit.bed ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958.fasta <span class="op">&gt;</span> cds_chrom_all.fna</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>combine with predicted CDS from eris, and run clustering using mmseq2 again</p>
<div id="166f92f9" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>cat cds_chrom_all.fna cds_gfa_shovill_is.fna <span class="op">&gt;</span> combined_cds_truth_eris.fna</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>mmseqs easy<span class="op">-</span>cluster combined_cds_truth_eris.fna clusterCDS tmp <span class="op">--</span><span class="bu">min</span><span class="op">-</span>seq<span class="op">-</span><span class="bu">id</span> <span class="fl">0.8</span> <span class="op">-</span>c <span class="fl">0.8</span> <span class="op">-</span>s <span class="dv">7</span> <span class="op">--</span>threads <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="ae9bfbe0" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> defaultdict(<span class="bu">list</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"clusterCDS_cluster.tsv"</span>) <span class="im">as</span> entries:</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> entry <span class="kw">in</span> entries.readlines():</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    cluster, member <span class="op">=</span> entry.split(<span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    clusters[cluster].append(member)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"There are </span><span class="sc">{</span><span class="bu">len</span>(clusters)<span class="sc">}</span><span class="ss"> clusters"</span>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co"># classify clusters</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>truth_only <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>predicted_only <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>both <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>truth_clusters <span class="op">=</span> []</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>predicted_clusters <span class="op">=</span> []</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>both_clusters <span class="op">=</span> []</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cluster_id, members <span class="kw">in</span> clusters.items():</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    has_truth <span class="op">=</span> <span class="bu">any</span>(m.startswith(<span class="st">"HG941718.1"</span>) <span class="cf">for</span> m <span class="kw">in</span> members)</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>    has_predicted <span class="op">=</span> <span class="bu">any</span>(<span class="kw">not</span> m.startswith(<span class="st">"HG941718.1"</span>) <span class="cf">for</span> m <span class="kw">in</span> members)</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> has_truth <span class="kw">and</span> has_predicted:</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>        both <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>        both_clusters.append(cluster_id)</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> has_truth:</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>        truth_only <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>        truth_clusters.append(cluster_id)</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> has_predicted:</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>        predicted_only <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>        predicted_clusters.append(cluster_id)</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib_venn <span class="im">import</span> venn2</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a><span class="co"># sizes</span></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>only_truth <span class="op">=</span> <span class="bu">len</span>(truth_clusters)</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>only_predicted <span class="op">=</span> <span class="bu">len</span>(predicted_clusters)</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>overlap <span class="op">=</span> <span class="bu">len</span>(both_clusters)</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Venn diagram</span></span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">5</span>,<span class="dv">5</span>))</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>venn2(subsets<span class="op">=</span>(only_truth, only_predicted, overlap),</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>      set_labels<span class="op">=</span>(<span class="st">"TRUTH"</span>, <span class="st">"predicted CDS"</span>))</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Cluster overlap"</span>)</span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters with both TRUTH and predicted:"</span>, both)</span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters only TRUTH:"</span>, truth_only)</span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters only predicted:"</span>, predicted_only)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 300 clusters</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="week11_files/figure-html/cell-18-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Clusters with both TRUTH and predicted: 14
Clusters only TRUTH: 127
Clusters only predicted: 159</code></pre>
</div>
</div>
<p>print cluster that have intersection from both:</p>
<div id="a6f29e93" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> clust, mem <span class="kw">in</span> clusters.items():</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  has_hg <span class="op">=</span> <span class="bu">any</span>(e.startswith(<span class="st">"HG"</span>) <span class="cf">for</span> e <span class="kw">in</span> mem)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  has_non_hg <span class="op">=</span> <span class="bu">any</span>(<span class="kw">not</span> e.startswith(<span class="st">"HG"</span>) <span class="cf">for</span> e <span class="kw">in</span> mem)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> has_hg <span class="kw">and</span> has_non_hg:</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Cluster </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>mem<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cluster 1: ['HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647529-1648819:-\n', 'HG941718.1_1647550-1648819:-\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', 'HG941718.1_1647529-1648819:+\n', '1245096_04606|1245096|-|inside|same_strand|ISEc1\n']
Cluster 2: ['HG941718.1_2272036-2273665:-\n', 'HG941718.1_3112409-3114403:-\n', 'HG941718.1_3112918-3114403:+\n', '1244742_00934|1244742|-|inside|same_strand|ISEc12\n', 'HG941718.1_4972537-4974384:+\n']
Cluster 3: ['HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', 'HG941718.1_3295104-3295881:-\n', '1243600_00327|1243600|-|inside|same_strand|ISKox3\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295792:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_3295104-3295881:+\n', 'HG941718.1_5014814-5015463:+\n']
Cluster 4: ['HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', 'HG941718.1_3313144-3314364:+\n', '1242602_00264|1242602|-|inside|same_strand|IS30\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n', 'HG941718.1_3313144-3314364:-\n']
Cluster 5: ['HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_3314363-3315303:-\n', 'HG941718.1_4942386-4943379:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', 'HG941718.1_3314363-3315303:+\n', '1243758_00330|1243758|-|inside|same_strand|ISSd1\n']
Cluster 6: ['1244700_00882|1244700|-|inside|same_strand|ISEc23\n', 'HG941718.1_233728-234240:+\n']
Cluster 7: ['1244816_01151|1244816|-|inside|same_strand|ISEc23\n', 'HG941718.1_2266953-2268365:+\n']
Cluster 8: ['HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', 'HG941718.1_4156067-4156581:-\n', '1245106_04639|1245106|-|inside|same_strand|ISSen10\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n', 'HG941718.1_4156067-4156581:+\n']
Cluster 9: ['1244160_00403|1244160|-|inside|same_strand|IS1397\n', 'HG941718.1_1997568-1997936:+\n']
Cluster 10: ['1244402_00441|1244402|-|inside|same_strand|IS100kyp\n', 'HG941718.1_2252366-2253189:-\n']
Cluster 11: ['1244638_00699|1244638|-|inside|same_strand|ISEc53\n', 'HG941718.1_5014814-5016081:+\n']
Cluster 12: ['1244656_00846|1244656|-|inside|same_strand|ISCro1\n', 'HG941718.1_4172218-4173827:-\n']
Cluster 13: ['HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:-\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', 'HG941718.1_4937433-4938940:+\n', '1245048_03746|1245048|-|inside|same_strand|ISEc9\n']
Cluster 14: ['HG941718.1_4956001-4956763:-\n', '1244320_00405|1244320|-|inside|same_strand|ISEc8\n']</code></pre>
</div>
</div>
<div id="e792fc25" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>grep <span class="st">"^HG941718</span><span class="er">\</span><span class="st">.1"</span> ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958_genomic_sorted.cds.edit.bed <span class="op">|</span> bedtools slop <span class="op">-</span>i <span class="op">-</span> <span class="op">-</span>g ec958.genome.size <span class="op">-</span>b <span class="dv">100000</span> <span class="op">|</span> bedtools intersect <span class="op">-</span>a <span class="op">-</span> <span class="op">-</span>b ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>ec958_IS.reannotated.<span class="bu">sorted</span>.bed <span class="op">&gt;</span> temp</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>seqkit subseq <span class="op">--</span>bed temp ..<span class="op">/</span>..<span class="op">/</span>data<span class="op">/</span>ecoli<span class="op">/</span>EC958.fasta <span class="op">&gt;</span> cds_truth_with_is_intersect.fna</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>rm temp</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>cat cds_truth_with_is_intersect.fna cds_gfa_shovill_is.fna <span class="op">&gt;</span> combined_cds_truth_eris.fna</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>mmseqs easy<span class="op">-</span>cluster combined_cds_truth_eris.fna clusterCDS tmp <span class="op">--</span><span class="bu">min</span><span class="op">-</span>seq<span class="op">-</span><span class="bu">id</span> <span class="fl">0.8</span> <span class="op">-</span>c <span class="fl">0.8</span> <span class="op">-</span>s <span class="dv">7</span> <span class="op">--</span>threads <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="5468cba7" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> defaultdict(<span class="bu">list</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"clusterCDS_cluster.tsv"</span>) <span class="im">as</span> entries:</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> entry <span class="kw">in</span> entries.readlines():</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    cluster, member <span class="op">=</span> entry.split(<span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    clusters[cluster].append(member)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"There are </span><span class="sc">{</span><span class="bu">len</span>(clusters)<span class="sc">}</span><span class="ss"> clusters"</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co"># classify clusters</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>truth_only <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>predicted_only <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>both <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>truth_clusters <span class="op">=</span> []</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>predicted_clusters <span class="op">=</span> []</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>both_clusters <span class="op">=</span> []</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cluster_id, members <span class="kw">in</span> clusters.items():</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    has_truth <span class="op">=</span> <span class="bu">any</span>(m.startswith(<span class="st">"HG941718.1"</span>) <span class="cf">for</span> m <span class="kw">in</span> members)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>    has_predicted <span class="op">=</span> <span class="bu">any</span>(<span class="kw">not</span> m.startswith(<span class="st">"HG941718.1"</span>) <span class="cf">for</span> m <span class="kw">in</span> members)</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> has_truth <span class="kw">and</span> has_predicted:</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>        both <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>        both_clusters.append(cluster_id)</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> has_truth:</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>        truth_only <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>        truth_clusters.append(cluster_id)</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> has_predicted:</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>        predicted_only <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>        predicted_clusters.append(cluster_id)</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib_venn <span class="im">import</span> venn2</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a><span class="co"># sizes</span></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>only_truth <span class="op">=</span> <span class="bu">len</span>(truth_clusters)</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>only_predicted <span class="op">=</span> <span class="bu">len</span>(predicted_clusters)</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>overlap <span class="op">=</span> <span class="bu">len</span>(both_clusters)</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Venn diagram</span></span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">5</span>,<span class="dv">5</span>))</span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>venn2(subsets<span class="op">=</span>(only_truth, only_predicted, overlap),</span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>      set_labels<span class="op">=</span>(<span class="st">"TRUTH"</span>, <span class="st">"predicted CDS"</span>))</span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Cluster overlap"</span>)</span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters with both TRUTH and predicted:"</span>, both)</span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters only TRUTH:"</span>, truth_only)</span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Clusters only predicted:"</span>, predicted_only)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 300 clusters</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="week11_files/figure-html/cell-21-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Clusters with both TRUTH and predicted: 14
Clusters only TRUTH: 127
Clusters only predicted: 159</code></pre>
</div>
</div>


</section>
</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/adimascf\.github\.io\/logbook-IS\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>